### ISSUE TITLE
ES Ashura uses S3 Peelout & Snowboarding sprites when set to S2A Sprites

### ISSUE THREAD

**Issue by RoyalGuard1991** [sonic-blue-speed/ES-3D-in-2D-Ashura#1]
S3AIR Version: v22.09.10.0 (latest stable release)

ES 3D2D Ashura Version: v2.03.1

Mods Active:
ES 3D2D Ashura
Extra Save Slots
S3C Level Select +
Extra Character Slots Unlimited

When Ashura's art style is set to "Sonic 2 Absolute", his Peelout sprites use the Sonic 3 art style.

![S2A_Ashura_ArtStyle_Inconsistency](https://github.com/sonic-blue-speed/ES-3D-in-2D-Ashura/assets/117999968/72f7730d-3ced-4518-be80-a9694b7e0877)

**Comment by RoyalGuard1991** [comment]
The same applies to the Snowboarding section at the start of ICZ1. 
When Ashura's art style is set to "Sonic 2 Absolute", his snowboarding sprites use the Sonic 3 art style.

**Comment by SaturnDreemurr32X** [comment]
> S3AIR Version: v22.09.10.0 (latest stable release)
> 
> ES 3D2D Ashura Version: v2.03.1
> 
> Mods Active: ES 3D2D Ashura Extra Save Slots S3C Level Select + Extra Character Slots Unlimited
> 
> When Ashura's art style is set to "Sonic 2 Absolute", his Peelout sprites use the Sonic 3 art style.
> 
> ![S2A_Ashura_ArtStyle_Inconsistency](https://user-images.githubusercontent.com/117999968/247009072-72f7730d-3ced-4518-be80-a9694b7e0877.PNG)

Yeah that's normal, the team is trying to fix this i think.

**Comment by SaturnDreemurr32X** [comment]
THIS HAS BEEN FIXED!
NEXT UPDATE IT WILL BE FIXED but i yet have to implement sonic 2 peelout
