### ISSUE TITLE
ES Ashura Missing Fire Shield Sprites

### ISSUE THREAD

**Issue by RoyalGuard1991** [sonic-blue-speed/ES-3D-in-2D-Ashura#2]
S3AIR Version: v22.09.10.0 (latest stable release)

ES 3D2D Ashura Version: v2.03.1

Mods Active:
ES 3D2D Ashura
Extra Save Slots
S3C Level Select +
Extra Character Slots Unlimited
Monitors HUD

When ES 3D2D Ashura collects a Fire Shield, he is given immunity to fire damage, but the Fire Shield's sprites do not display.
Monitors HUD mod used for demonstration purposes to show that a Fire Shield was collected.

![Ashura_Invisible_Fire_Shield](https://github.com/sonic-blue-speed/ES-3D-in-2D-Ashura/assets/117999968/2d2f02db-2341-4926-bac0-a32223ec203f)

**Comment by SaturnDreemurr32X** [comment]
> S3AIR Version: v22.09.10.0 (latest stable release)
> 
> ES 3D2D Ashura Version: v2.03.1
> 
> Mods Active: ES 3D2D Ashura Extra Save Slots S3C Level Select + Extra Character Slots Unlimited Monitors HUD
> 
> When ES 3D2D Ashura collects a Fire Shield, he is given immunity to fire damage, but the Fire Shield's sprites do not display. Monitors HUD mod used for demonstration purposes to show that a Fire Shield was collected.
> 
> ![Ashura_Invisible_Fire_Shield](https://user-images.githubusercontent.com/117999968/247011173-2d2f02db-2341-4926-bac0-a32223ec203f.PNG)

If you have any other fire shield colors it won't appear but if you have the normal one it does

**Comment by sonic-blue-speed** [comment]
There is no more shieldmoders you can just use the shields by themselves because Ashura has access to all the elemental Shield without getting them

**Comment by sonic-blue-speed** [comment]
That should solve this problem
