### ISSUE TITLE
ES Ashura Cutscene Softlock in AIZ2 Knuckles Route

### ISSUE THREAD

**Issue by RoyalGuard1991** [sonic-blue-speed/ES-3D-in-2D-Ashura#3]
S3AIR Version: v22.09.10.0 (latest stable release)

ES 3D2D Ashura Version: v2.03.1

Mods Active:
ES 3D2D Ashura
Extra Save Slots
S3C Level Select +
Extra Character Slots Unlimited

When ES 3D2D Ashura reaches the boss of AIZ2 on the Knuckles Route, the water level rises when it probably shouldn't.
If you defeat the boss and trigger the cutscene with the Water Shield active, the game softlocks.
If you defeat the boss and trigger the cutscene without the Water Shield active, you drown during the cutscene and are sent back to the last checkpoint.
Returning to the Save Select after the cutscene softlock will have the ES Ashura save file set to HCZ.

![Ashura_AIZ2K_Cutscene_Softlock](https://github.com/sonic-blue-speed/ES-3D-in-2D-Ashura/assets/117999968/2950950f-5a74-438a-934f-c63706c1d4ec)

**Comment by RoyalGuard1991** [comment]
Cutscene still softlocks as of ES 3D2D Ashura v2.2.1, but it looks like the rising water might be fixed.

![Softlock_AIZ2K_Cutscene](https://github.com/sonic-blue-speed/ES-3D-in-2D-Ashura/assets/117999968/532b8d48-ae9c-4b4d-b3cd-21928ee30b0c)

**Comment by SaturnDreemurr32X** [comment]
Fixed by JC
