### ISSUE TITLE
ES Ashura Level Reload Softlock If Tails touches ground in CNZ1 or MHZ1

### ISSUE THREAD

**Issue by RoyalGuard1991** [sonic-blue-speed/ES-3D-in-2D-Ashura#4]
S3AIR Version: v22.09.10.0 (latest stable release)

ES 3D2D Ashura Version: v2.03.1

Mods Active:
ES 3D2D Ashura
Extra Save Slots
S3C Level Select +
Extra Character Slots Unlimited

Upon entering CNZ1 with Ashura riding Tails, the moment Tails lands on the ground, the level restarts itself in an infinite loop, which can only be escaped by closing the game, as far as I'm aware.

The only way to progress the game is to get away from Tails as fast as possible as soon as the level starts, so that Tails unloads before touching the ground.

**Comment by sonic-blue-speed** [comment]
Tails is not in the update

**Comment by sonic-blue-speed** [comment]
He is in the update

**Comment by RoyalGuard1991** [comment]
CNZ1 Tails Softlock can still occur in ES 3D2D Ashura v2.2.1.

![CNZ1 Tails Lands Softlock](https://github.com/sonic-blue-speed/ES-3D-in-2D-Ashura/assets/117999968/bd2f30da-0186-482f-a54d-f6ef030689f2)

**Comment by SaturnDreemurr32X** [comment]
Partner option is removed now but you gotta wait
