### ISSUE TITLE
ES Ashura can't complete LRZ2 Knuckles Route without Shields or S/H Forms

### ISSUE THREAD

**Issue by RoyalGuard1991** [sonic-blue-speed/ES-3D-in-2D-Ashura#5]
S3AIR Version: v22.09.10.0 (latest stable release)

ES 3D2D Ashura Version: v2.03.1

Mods Active:
ES 3D2D Ashura
Extra Save Slots
S3C Level Select +
Extra Character Slots Unlimited

ES 3D2D Ashura can enter LRZ2 Knuckles Route, but is unable to complete the area using his own natural abilities, getting stuck in a room that requires traveling through the air vertically a greater distance than his normal jump height, or climbing the wall to complete.

This area is only possible to complete with Ashura using added jump height from Lightning Shield or Super/Hyper Forms, as far as I'm aware.

![Ashura_LRZ2K_Route_Oversight](https://github.com/sonic-blue-speed/ES-3D-in-2D-Ashura/assets/117999968/d5a68885-4942-46cd-a46e-1f50b8e77ce3)

**Comment by sonic-blue-speed** [comment]
You need update 2.2.1

**Comment by RoyalGuard1991** [comment]
That version was not available in the Releases when I downloaded it, but I will update it and look over the changes.

**Comment by RoyalGuard1991** [comment]
Still not possible for ES Ashura v2.2.1 to complete the LRZ2 Knuckles Route without powerups that increase his jump height.
Not sure why the character can enter the Knuckles Route, if he can't complete it without powerups.

![LRZ2K Level Oversight](https://github.com/sonic-blue-speed/ES-3D-in-2D-Ashura/assets/117999968/9d7ec8f2-e709-453b-9778-a58c1eb37f2c)

**Comment by SaturnDreemurr32X** [comment]
> That version was not available in the Releases when I downloaded it, but I will update it and look over the changes. Thank you.

Ok so uhh us devs always send each other new builds so uhh patience!
