### ISSUE TITLE
Sonic skin's Peel-out Brakes

### ISSUE THREAD

**Issue by Baconfann707** [sonic-blue-speed/ES-3D-in-2D-Ashura#6]
when the mod is on the top of the skin dose the peel-out turn into the normal sonic 3 peel-out and with some skin the pallet brakes and if the skin is above the mod its goes back to normal but Ashura ballet brake and look like a normal sonic

**Comment by SaturnDreemurr32X** [comment]
Can you explain it simply? I can't really understand but if you're talking that it turns a skin into the ashura peelout, it probally doesnt since of course this is an extra slot and wont effect the vanilla sonic nor skins.
